IMG_OBJ=media/eagle.o media/redbrick.o media/purplestone.o media/greystone.o media/bluestone.o media/mossy.o media/wood.o media/colorstone.o
OBJ_FILES=wolf.o $(IMG_OBJ) $(SOUND_OBJ)
ELF_FILE=wolf

include ../../app.mk