IMG_OBJ=media/sprite.o
SOUND_OBJ=media/fastinvader1.o media/fastinvader2.o media/fastinvader3.o media/fastinvader4.o media/invaderkilled.o media/shoot.o
OBJ_FILES=si.o $(IMG_OBJ) $(SOUND_OBJ)
ELF_FILE=si

include ../../makefiles/app.mk