set -v
rm -rf    .svn
rm -rf    etc/.svn
rm -rf    libgloss/spu/.svn
rm -rf    libgloss/arm/.svn
rm -rf    libgloss/rx/.svn
rm -rf    libgloss/bfin/include/.svn
rm -rf    libgloss/bfin/include/sys/.svn
rm -rf    libgloss/bfin/.svn
rm -rf    libgloss/cris/.svn
rm -rf    libgloss/microblaze/.svn
rm -rf    libgloss/i386/.svn
rm -rf    libgloss/rs6000/.svn
rm -rf    libgloss/mt/.svn
rm -rf    libgloss/xstormy16/.svn
rm -rf    libgloss/sparc_leon/.svn
rm -rf    libgloss/sparc_leon/asm-leon/.svn
rm -rf    libgloss/mn10300/.svn
rm -rf    libgloss/.svn
rm -rf    libgloss/crx/.svn
rm -rf    libgloss/aarch64/.svn
rm -rf    libgloss/aarch64/cpu-init/.svn
rm -rf    libgloss/fr30/.svn
rm -rf    libgloss/frv/.svn
rm -rf    libgloss/m68hc11/.svn
rm -rf    libgloss/m68k/.svn
rm -rf    libgloss/m32c/.svn
rm -rf    libgloss/moxie/.svn
rm -rf    libgloss/testsuite/libgloss.all/.svn
rm -rf    libgloss/testsuite/.svn
rm -rf    libgloss/testsuite/lib/.svn
rm -rf    libgloss/testsuite/config/.svn
rm -rf    libgloss/epiphany/.svn
rm -rf    libgloss/sparc/libsys/.svn
rm -rf    libgloss/sparc/.svn
rm -rf    libgloss/sh/.svn
rm -rf    libgloss/doc/.svn
rm -rf    libgloss/m32r/.svn
rm -rf    libgloss/wince/.svn
rm -rf    libgloss/d30v/.svn
rm -rf    libgloss/v850/.svn
rm -rf    libgloss/v850/sys/.svn
rm -rf    libgloss/lm32/.svn
rm -rf    libgloss/mips/.svn
rm -rf    libgloss/i960/.svn
rm -rf    libgloss/hp74x/.svn
rm -rf    libgloss/rl78/.svn
rm -rf    libgloss/config/.svn
rm -rf    libgloss/mep/.svn
rm -rf    libgloss/tic6x/.svn
rm -rf    libgloss/cr16/.svn
rm -rf    libgloss/cr16/sys/.svn
rm -rf    libgloss/mn10200/.svn
rm -rf    libgloss/iq2000/.svn
rm -rf    libgloss/mcore/.svn
rm -rf    libgloss/xc16x/.svn
rm -rf    libgloss/xc16x/sys/.svn
rm -rf    libgloss/libnosys/.svn
rm -rf    libgloss/pa/.svn
rm -rf    texinfo/.svn
rm -rf    config/.svn
rm -rf    newlib/iconvdata/.svn
rm -rf    newlib/.svn
rm -rf    newlib/libm/.svn
rm -rf    newlib/libm/test/.svn
rm -rf    newlib/libm/machine/spu/headers/.svn
rm -rf    newlib/libm/machine/spu/.svn
rm -rf    newlib/libm/machine/arm/.svn
rm -rf    newlib/libm/machine/i386/.svn
rm -rf    newlib/libm/machine/.svn
rm -rf    newlib/libm/machine/aarch64/.svn
rm -rf    newlib/libm/complex/.svn
rm -rf    newlib/libm/mathfp/.svn
rm -rf    newlib/libm/common/.svn
rm -rf    newlib/libm/math/.svn
rm -rf    newlib/libc/signal/.svn
rm -rf    newlib/libc/unix/.svn
rm -rf    newlib/libc/locale/.svn
rm -rf    newlib/libc/include/.svn
rm -rf    newlib/libc/include/machine/.svn
rm -rf    newlib/libc/include/sys/.svn
rm -rf    newlib/libc/include/rpc/.svn
rm -rf    newlib/libc/.svn
rm -rf    newlib/libc/errno/.svn
rm -rf    newlib/libc/iconv/ccs/binary/.svn
rm -rf    newlib/libc/iconv/ccs/.svn
rm -rf    newlib/libc/iconv/ces/.svn
rm -rf    newlib/libc/iconv/.svn
rm -rf    newlib/libc/iconv/lib/.svn
rm -rf    newlib/libc/stdlib/.svn
rm -rf    newlib/libc/stdio64/.svn
rm -rf    newlib/libc/time/.svn
rm -rf    newlib/libc/string/.svn
rm -rf    newlib/libc/search/.svn
rm -rf    newlib/libc/machine/necv70/.svn
rm -rf    newlib/libc/machine/necv70/machine/.svn
rm -rf    newlib/libc/machine/spu/include/.svn
rm -rf    newlib/libc/machine/spu/.svn
rm -rf    newlib/libc/machine/spu/machine/.svn
rm -rf    newlib/libc/machine/spu/sys/.svn
rm -rf    newlib/libc/machine/arm/.svn
rm -rf    newlib/libc/machine/arm/machine/.svn
rm -rf    newlib/libc/machine/tic4x/.svn
rm -rf    newlib/libc/machine/rx/.svn
rm -rf    newlib/libc/machine/bfin/.svn
rm -rf    newlib/libc/machine/cris/include/.svn
rm -rf    newlib/libc/machine/cris/.svn
rm -rf    newlib/libc/machine/cris/sys/.svn
rm -rf    newlib/libc/machine/microblaze/.svn
rm -rf    newlib/libc/machine/i386/.svn
rm -rf    newlib/libc/machine/i386/machine/.svn
rm -rf    newlib/libc/machine/mt/.svn
rm -rf    newlib/libc/machine/xstormy16/.svn
rm -rf    newlib/libc/machine/mn10300/.svn
rm -rf    newlib/libc/machine/.svn
rm -rf    newlib/libc/machine/crx/.svn
rm -rf    newlib/libc/machine/crx/sys/.svn
rm -rf    newlib/libc/machine/aarch64/.svn
rm -rf    newlib/libc/machine/aarch64/machine/.svn
rm -rf    newlib/libc/machine/fr30/.svn
rm -rf    newlib/libc/machine/frv/.svn
rm -rf    newlib/libc/machine/m68hc11/.svn
rm -rf    newlib/libc/machine/h8300/.svn
rm -rf    newlib/libc/machine/m68k/.svn
rm -rf    newlib/libc/machine/m32c/.svn
rm -rf    newlib/libc/machine/moxie/.svn
rm -rf    newlib/libc/machine/tic80/.svn
rm -rf    newlib/libc/machine/epiphany/.svn
rm -rf    newlib/libc/machine/epiphany/machine/.svn
rm -rf    newlib/libc/machine/hppa/.svn
rm -rf    newlib/libc/machine/powerpc/.svn
rm -rf    newlib/libc/machine/powerpc/machine/.svn
rm -rf    newlib/libc/machine/sparc/.svn
rm -rf    newlib/libc/machine/sparc/machine/.svn
rm -rf    newlib/libc/machine/sh/.svn
rm -rf    newlib/libc/machine/m88k/.svn
rm -rf    newlib/libc/machine/x86_64/.svn
rm -rf    newlib/libc/machine/m32r/.svn
rm -rf    newlib/libc/machine/z8k/.svn
rm -rf    newlib/libc/machine/d30v/.svn
rm -rf    newlib/libc/machine/h8500/.svn
rm -rf    newlib/libc/machine/v850/.svn
rm -rf    newlib/libc/machine/lm32/.svn
rm -rf    newlib/libc/machine/mips/.svn
rm -rf    newlib/libc/machine/mips/machine/.svn
rm -rf    newlib/libc/machine/xscale/.svn
rm -rf    newlib/libc/machine/xscale/machine/.svn
rm -rf    newlib/libc/machine/i960/.svn
rm -rf    newlib/libc/machine/rl78/.svn
rm -rf    newlib/libc/machine/mep/.svn
rm -rf    newlib/libc/machine/tic6x/.svn
rm -rf    newlib/libc/machine/cr16/.svn
rm -rf    newlib/libc/machine/cr16/sys/.svn
rm -rf    newlib/libc/machine/mn10200/.svn
rm -rf    newlib/libc/machine/iq2000/.svn
rm -rf    newlib/libc/machine/xc16x/.svn
rm -rf    newlib/libc/machine/w65/.svn
rm -rf    newlib/libc/machine/a29k/.svn
rm -rf    newlib/libc/machine/d10v/.svn
rm -rf    newlib/libc/ctype/.svn
rm -rf    newlib/libc/posix/.svn
rm -rf    newlib/libc/reent/.svn
rm -rf    newlib/libc/xdr/.svn
rm -rf    newlib/libc/argz/.svn
rm -rf    newlib/libc/sys/sysvi386/.svn
rm -rf    newlib/libc/sys/sysvi386/sys/.svn
rm -rf    newlib/libc/sys/arm/.svn
rm -rf    newlib/libc/sys/arm/sys/.svn
rm -rf    newlib/libc/sys/z8ksim/.svn
rm -rf    newlib/libc/sys/z8ksim/sys/.svn
rm -rf    newlib/libc/sys/m88kbug/.svn
rm -rf    newlib/libc/sys/m88kbug/sys/.svn
rm -rf    newlib/libc/sys/mmixware/.svn
rm -rf    newlib/libc/sys/mmixware/sys/.svn
rm -rf    newlib/libc/sys/a29khif/.svn
rm -rf    newlib/libc/sys/a29khif/sys/.svn
rm -rf    newlib/libc/sys/.svn
rm -rf    newlib/libc/sys/sysnec810/.svn
rm -rf    newlib/libc/sys/tic80/.svn
rm -rf    newlib/libc/sys/epiphany/.svn
rm -rf    newlib/libc/sys/linux/bits/.svn
rm -rf    newlib/libc/sys/linux/linuxthreads/bits/.svn
rm -rf    newlib/libc/sys/linux/linuxthreads/.svn
rm -rf    newlib/libc/sys/linux/linuxthreads/machine/i386/.svn
rm -rf    newlib/libc/sys/linux/linuxthreads/machine/.svn
rm -rf    newlib/libc/sys/linux/linuxthreads/machine/generic/.svn
rm -rf    newlib/libc/sys/linux/include/netinet/.svn
rm -rf    newlib/libc/sys/linux/include/arpa/.svn
rm -rf    newlib/libc/sys/linux/include/.svn
rm -rf    newlib/libc/sys/linux/include/netns/.svn
rm -rf    newlib/libc/sys/linux/include/netinet6/.svn
rm -rf    newlib/libc/sys/linux/include/net/.svn
rm -rf    newlib/libc/sys/linux/include/rpc/.svn
rm -rf    newlib/libc/sys/linux/.svn
rm -rf    newlib/libc/sys/linux/argp/.svn
rm -rf    newlib/libc/sys/linux/intl/.svn
rm -rf    newlib/libc/sys/linux/iconv/.svn
rm -rf    newlib/libc/sys/linux/cmath/.svn
rm -rf    newlib/libc/sys/linux/machine/i386/include/.svn
rm -rf    newlib/libc/sys/linux/machine/i386/.svn
rm -rf    newlib/libc/sys/linux/machine/.svn
rm -rf    newlib/libc/sys/linux/dl/.svn
rm -rf    newlib/libc/sys/linux/net/.svn
rm -rf    newlib/libc/sys/linux/net/nscd/.svn
rm -rf    newlib/libc/sys/linux/sys/.svn
rm -rf    newlib/libc/sys/sh/.svn
rm -rf    newlib/libc/sys/sh/sys/.svn
rm -rf    newlib/libc/sys/sysvnecv70/.svn
rm -rf    newlib/libc/sys/sysmec/.svn
rm -rf    newlib/libc/sys/sysmec/sys/.svn
rm -rf    newlib/libc/sys/h8300hms/.svn
rm -rf    newlib/libc/sys/h8300hms/sys/.svn
rm -rf    newlib/libc/sys/rtems/include/.svn
rm -rf    newlib/libc/sys/rtems/.svn
rm -rf    newlib/libc/sys/rtems/machine/.svn
rm -rf    newlib/libc/sys/rtems/sys/.svn
rm -rf    newlib/libc/sys/netware/.svn
rm -rf    newlib/libc/sys/sysnecv850/.svn
rm -rf    newlib/libc/sys/sysnecv850/sys/.svn
rm -rf    newlib/libc/sys/arc/.svn
rm -rf    newlib/libc/sys/arc/sys/.svn
rm -rf    newlib/libc/sys/sparc64/.svn
rm -rf    newlib/libc/sys/sparc64/sys/.svn
rm -rf    newlib/libc/sys/sun4/.svn
rm -rf    newlib/libc/sys/sun4/sys/.svn
rm -rf    newlib/libc/sys/w65/.svn
rm -rf    newlib/libc/sys/w65/sys/.svn
rm -rf    newlib/libc/sys/decstation/.svn
rm -rf    newlib/libc/sys/decstation/sys/.svn
rm -rf    newlib/libc/sys/h8500hms/.svn
rm -rf    newlib/libc/sys/d10v/.svn
rm -rf    newlib/libc/sys/d10v/sys/.svn
rm -rf    newlib/libc/sys/rdos/.svn
rm -rf    newlib/libc/syscalls/.svn
rm -rf    newlib/libc/stdio/.svn
rm -rf    newlib/libc/misc/.svn
rm -rf    newlib/testsuite/include/.svn
rm -rf    newlib/testsuite/newlib.search/.svn
rm -rf    newlib/testsuite/newlib.wctype/.svn
rm -rf    newlib/testsuite/.svn
rm -rf    newlib/testsuite/newlib.elix/.svn
rm -rf    newlib/testsuite/lib/.svn
rm -rf    newlib/testsuite/newlib.locale/.svn
rm -rf    newlib/testsuite/newlib.stdlib/.svn
rm -rf    newlib/testsuite/config/.svn
rm -rf    newlib/testsuite/newlib.string/.svn
rm -rf    newlib/testsuite/newlib.iconv/.svn
rm -rf    newlib/testsuite/newlib.stdio/.svn
rm -rf    newlib/doc/.svn

