ELF_FILE=bemacs
OBJ_FILES=readline.o basic.o buffer.o display.o file.o fileio.o line.o main.o random.o region.o search.o tcap.o termio.o window.o word.o dirname.o
LIBS=-lreadline

include ../../makefiles/app.mk
OPTIMIZE=-O2
