LIBC_OBJS=libc/lib_a-_Exit.o\
libc/lib_a-__adjust.o\
libc/lib_a-__atexit.o\
libc/lib_a-__call_atexit.o\
libc/lib_a-__dprintf.o\
libc/lib_a-__exp10.o\
libc/lib_a-__ten_mu.o\
libc/lib_a-_isatty.o\
libc/lib_a-a64l.o\
libc/lib_a-abort.o\
libc/lib_a-abs.o\
libc/lib_a-argz_add.o\
libc/lib_a-argz_add_sep.o\
libc/lib_a-argz_append.o\
libc/lib_a-argz_count.o\
libc/lib_a-argz_create.o\
libc/lib_a-argz_create_sep.o\
libc/lib_a-argz_delete.o\
libc/lib_a-argz_extract.o\
libc/lib_a-argz_insert.o\
libc/lib_a-argz_next.o\
libc/lib_a-argz_replace.o\
libc/lib_a-argz_stringify.o\
libc/lib_a-asctime.o\
libc/lib_a-asctime_r.o\
libc/lib_a-asiprintf.o\
libc/lib_a-asniprintf.o\
libc/lib_a-asnprintf.o\
libc/lib_a-asprintf.o\
libc/lib_a-assert.o\
libc/lib_a-atexit.o\
libc/lib_a-atof.o\
libc/lib_a-atoff.o\
libc/lib_a-atoi.o\
libc/lib_a-atol.o\
libc/lib_a-atoll.o\
libc/lib_a-bcmp.o\
libc/lib_a-bcopy.o\
libc/lib_a-bsearch.o\
libc/lib_a-btowc.o\
libc/lib_a-buf_findstr.o\
libc/lib_a-bzero.o\
libc/lib_a-calloc.o\
libc/lib_a-callocr.o\
libc/lib_a-cfreer.o\
libc/lib_a-clearerr.o\
libc/lib_a-clock.o\
libc/lib_a-closedir.o\
libc/lib_a-closer.o\
libc/lib_a-collate.o\
libc/lib_a-collcmp.o\
libc/lib_a-creat.o\
libc/lib_a-ctime.o\
libc/lib_a-ctime_r.o\
libc/lib_a-ctype_.o\
libc/lib_a-cxa_atexit.o\
libc/lib_a-cxa_finalize.o\
libc/lib_a-difftime.o\
libc/lib_a-diprintf.o\
libc/lib_a-div.o\
libc/lib_a-dprintf.o\
libc/lib_a-drand48.o\
libc/lib_a-dtoa.o\
libc/lib_a-dtoastub.o\
libc/lib_a-dummy.o\
libc/lib_a-ecvtbuf.o\
libc/lib_a-efgcvt.o\
libc/lib_a-environ.o\
libc/lib_a-envlock.o\
libc/lib_a-envz_add.o\
libc/lib_a-envz_entry.o\
libc/lib_a-envz_get.o\
libc/lib_a-envz_merge.o\
libc/lib_a-envz_remove.o\
libc/lib_a-envz_strip.o\
libc/lib_a-eprintf.o\
libc/lib_a-erand48.o\
libc/lib_a-errno.o\
libc/lib_a-execl.o\
libc/lib_a-execle.o\
libc/lib_a-execlp.o\
libc/lib_a-execr.o\
libc/lib_a-execv.o\
libc/lib_a-execve.o\
libc/lib_a-execvp.o\
libc/lib_a-exit.o\
libc/lib_a-fclose.o\
libc/lib_a-fcloseall.o\
libc/lib_a-fcntlr.o\
libc/lib_a-fdopen.o\
libc/lib_a-feof.o\
libc/lib_a-ferror.o\
libc/lib_a-fflush.o\
libc/lib_a-ffs.o\
libc/lib_a-fgetc.o\
libc/lib_a-fgetpos.o\
libc/lib_a-fgets.o\
libc/lib_a-fgetwc.o\
libc/lib_a-fgetws.o\
libc/lib_a-fileno.o\
libc/lib_a-findfp.o\
libc/lib_a-fini.o\
libc/lib_a-fiprintf.o\
libc/lib_a-fiscanf.o\
libc/lib_a-fix_grouping.o\
libc/lib_a-flags.o\
libc/lib_a-fmemopen.o\
libc/lib_a-fnmatch.o\
libc/lib_a-fopen.o\
libc/lib_a-fopencookie.o\
libc/lib_a-fprintf.o\
libc/lib_a-fpurge.o\
libc/lib_a-fputc.o\
libc/lib_a-fputs.o\
libc/lib_a-fputwc.o\
libc/lib_a-fputws.o\
libc/lib_a-fread.o\
libc/lib_a-freer.o\
libc/lib_a-freopen.o\
libc/lib_a-fscanf.o\
libc/lib_a-fseek.o\
libc/lib_a-fseeko.o\
libc/lib_a-fsetpos.o\
libc/lib_a-fstatr.o\
libc/lib_a-ftell.o\
libc/lib_a-ftello.o\
libc/lib_a-ftruncate.o\
libc/lib_a-funopen.o\
libc/lib_a-fvwrite.o\
libc/lib_a-fwalk.o\
libc/lib_a-fwide.o\
libc/lib_a-fwprintf.o\
libc/lib_a-fwrite.o\
libc/lib_a-fwscanf.o\
libc/lib_a-gdtoa-gethex.o\
libc/lib_a-gdtoa-hexnan.o\
libc/lib_a-getc.o\
libc/lib_a-getc_u.o\
libc/lib_a-getchar.o\
libc/lib_a-getchar_u.o\
libc/lib_a-getdelim.o\
libc/lib_a-getenv.o\
libc/lib_a-getenv_r.o\
libc/lib_a-getline.o\
libc/lib_a-getopt.o\
libc/lib_a-getreent.o\
libc/lib_a-gets.o\
libc/lib_a-getsubopt.o\
libc/lib_a-gettimeofdayr.o\
libc/lib_a-gettzinfo.o\
libc/lib_a-getw.o\
libc/lib_a-getwc.o\
libc/lib_a-getwchar.o\
libc/lib_a-glob.o\
libc/lib_a-gmtime.o\
libc/lib_a-gmtime_r.o\
libc/lib_a-hash.o\
libc/lib_a-hash_bigkey.o\
libc/lib_a-hash_buf.o\
libc/lib_a-hash_func.o\
libc/lib_a-hash_log2.o\
libc/lib_a-hash_page.o\
libc/lib_a-hcreate.o\
libc/lib_a-hcreate_r.o\
libc/lib_a-impure.o\
libc/lib_a-index.o\
libc/lib_a-init.o\
libc/lib_a-iprintf.o\
libc/lib_a-isalnum.o\
libc/lib_a-isalpha.o\
libc/lib_a-isascii.o\
libc/lib_a-isatty.o\
libc/lib_a-isattyr.o\
libc/lib_a-isblank.o\
libc/lib_a-iscanf.o\
libc/lib_a-iscntrl.o\
libc/lib_a-isdigit.o\
libc/lib_a-islower.o\
libc/lib_a-isprint.o\
libc/lib_a-ispunct.o\
libc/lib_a-isspace.o\
libc/lib_a-isupper.o\
libc/lib_a-iswalnum.o\
libc/lib_a-iswalpha.o\
libc/lib_a-iswblank.o\
libc/lib_a-iswcntrl.o\
libc/lib_a-iswctype.o\
libc/lib_a-iswdigit.o\
libc/lib_a-iswgraph.o\
libc/lib_a-iswlower.o\
libc/lib_a-iswprint.o\
libc/lib_a-iswpunct.o\
libc/lib_a-iswspace.o\
libc/lib_a-iswupper.o\
libc/lib_a-iswxdigit.o\
libc/lib_a-isxdigit.o\
libc/lib_a-jp2uc.o\
libc/lib_a-jrand48.o\
libc/lib_a-l64a.o\
libc/lib_a-labs.o\
libc/lib_a-lcltime.o\
libc/lib_a-lcltime_r.o\
libc/lib_a-lcong48.o\
libc/lib_a-lctype.o\
libc/lib_a-ldiv.o\
libc/lib_a-ldpart.o\
libc/lib_a-ldtoa.o\
libc/lib_a-linkr.o\
libc/lib_a-llabs.o\
libc/lib_a-lldiv.o\
libc/lib_a-lmessages.o\
libc/lib_a-lmonetary.o\
libc/lib_a-lnumeric.o\
libc/lib_a-locale.o\
libc/lib_a-lrand48.o\
libc/lib_a-lseekr.o\
libc/lib_a-makebuf.o\
libc/lib_a-malign.o\
libc/lib_a-malignr.o\
libc/lib_a-mallinfor.o\
libc/lib_a-malloc.o\
libc/lib_a-mallocr.o\
libc/lib_a-malloptr.o\
libc/lib_a-mallstatsr.o\
libc/lib_a-mblen.o\
libc/lib_a-mblen_r.o\
libc/lib_a-mbrlen.o\
libc/lib_a-mbrtowc.o\
libc/lib_a-mbsinit.o\
libc/lib_a-mbsnrtowcs.o\
libc/lib_a-mbsrtowcs.o\
libc/lib_a-mbstowcs.o\
libc/lib_a-mbstowcs_r.o\
libc/lib_a-mbtowc.o\
libc/lib_a-mbtowc_r.o\
libc/lib_a-memccpy.o\
libc/lib_a-memchr.o\
libc/lib_a-memcmp.o\
libc/lib_a-memcpy.o\
libc/lib_a-memmem.o\
libc/lib_a-memmove.o\
libc/lib_a-mempcpy.o\
libc/lib_a-memrchr.o\
libc/lib_a-memset.o\
libc/lib_a-mkdirr.o\
libc/lib_a-mktemp.o\
libc/lib_a-mktime.o\
libc/lib_a-mktm_r.o\
libc/lib_a-mlock.o\
libc/lib_a-mprec.o\
libc/lib_a-mrand48.o\
libc/lib_a-msize.o\
libc/lib_a-msizer.o\
libc/lib_a-mstats.o\
libc/lib_a-mtrim.o\
libc/lib_a-nl_langinfo.o\
libc/lib_a-nrand48.o\
libc/lib_a-on_exit.o\
libc/lib_a-open_memstream.o\
libc/lib_a-opendir.o\
libc/lib_a-openr.o\
libc/lib_a-perror.o\
libc/lib_a-popen.o\
libc/lib_a-printf.o\
libc/lib_a-psignal.o\
libc/lib_a-putc.o\
libc/lib_a-putc_u.o\
libc/lib_a-putchar.o\
libc/lib_a-putchar_u.o\
libc/lib_a-putenv.o\
libc/lib_a-putenv_r.o\
libc/lib_a-puts.o\
libc/lib_a-putw.o\
libc/lib_a-putwc.o\
libc/lib_a-putwchar.o\
libc/lib_a-pvallocr.o\
libc/lib_a-qsort.o\
libc/lib_a-raise.o\
libc/lib_a-rand.o\
libc/lib_a-rand48.o\
libc/lib_a-rand_r.o\
libc/lib_a-readdir.o\
libc/lib_a-readdir_r.o\
libc/lib_a-readr.o\
libc/lib_a-realloc.o\
libc/lib_a-reallocf.o\
libc/lib_a-reallocr.o\
libc/lib_a-reent.o\
libc/lib_a-refill.o\
libc/lib_a-regcomp.o\
libc/lib_a-regerror.o\
libc/lib_a-regexec.o\
libc/lib_a-regfree.o\
libc/lib_a-remove.o\
libc/lib_a-rename.o\
libc/lib_a-renamer.o\
libc/lib_a-rewind.o\
libc/lib_a-rewinddir.o\
libc/lib_a-rget.o\
libc/lib_a-rindex.o\
libc/lib_a-s_copysign.o\
libc/lib_a-s_finite.o\
libc/lib_a-s_fpclassify.o\
libc/lib_a-s_frexp.o\
libc/lib_a-s_infconst.o\
libc/lib_a-s_isinf.o\
libc/lib_a-s_isinfd.o\
libc/lib_a-s_isnan.o\
libc/lib_a-s_isnand.o\
libc/lib_a-s_ldexp.o\
libc/lib_a-s_modf.o\
libc/lib_a-s_nan.o\
libc/lib_a-s_scalbn.o\
libc/lib_a-sb_charsets.o\
libc/lib_a-sbrkr.o\
libc/lib_a-scandir.o\
libc/lib_a-scanf.o\
libc/lib_a-sccl.o\
libc/lib_a-seed48.o\
libc/lib_a-seekdir.o\
libc/lib_a-setbuf.o\
libc/lib_a-setbuffer.o\
libc/lib_a-setenv.o\
libc/lib_a-setenv_r.o\
libc/lib_a-setjmp.o\
libc/lib_a-setlinebuf.o\
libc/lib_a-setvbuf.o\
libc/lib_a-sf_copysign.o\
libc/lib_a-sf_finite.o\
libc/lib_a-sf_fpclassify.o\
libc/lib_a-sf_frexp.o\
libc/lib_a-sf_isinf.o\
libc/lib_a-sf_isinff.o\
libc/lib_a-sf_isnan.o\
libc/lib_a-sf_isnanf.o\
libc/lib_a-sf_ldexp.o\
libc/lib_a-sf_modf.o\
libc/lib_a-sf_nan.o\
libc/lib_a-sf_scalbn.o\
libc/lib_a-signal.o\
libc/lib_a-signalr.o\
libc/lib_a-signgam.o\
libc/lib_a-siprintf.o\
libc/lib_a-siscanf.o\
libc/lib_a-sleep.o\
libc/lib_a-sniprintf.o\
libc/lib_a-snprintf.o\
libc/lib_a-sprintf.o\
libc/lib_a-srand48.o\
libc/lib_a-sscanf.o\
libc/lib_a-statr.o\
libc/lib_a-stdio.o\
libc/lib_a-stpcpy.o\
libc/lib_a-stpncpy.o\
libc/lib_a-strcasecmp.o\
libc/lib_a-strcasestr.o\
libc/lib_a-strcat.o\
libc/lib_a-strchr.o\
libc/lib_a-strchrnul.o\
libc/lib_a-strcmp.o\
libc/lib_a-strcoll.o\
libc/lib_a-strcpy.o\
libc/lib_a-strcspn.o\
libc/lib_a-strdup.o\
libc/lib_a-strdup_r.o\
libc/lib_a-strerror.o\
libc/lib_a-strerror_r.o\
libc/lib_a-strftime.o\
libc/lib_a-strlcat.o\
libc/lib_a-strlcpy.o\
libc/lib_a-strlen.o\
libc/lib_a-strlwr.o\
libc/lib_a-strncasecmp.o\
libc/lib_a-strncat.o\
libc/lib_a-strncmp.o\
libc/lib_a-strncpy.o\
libc/lib_a-strndup.o\
libc/lib_a-strndup_r.o\
libc/lib_a-strnlen.o\
libc/lib_a-strpbrk.o\
libc/lib_a-strptime.o\
libc/lib_a-strrchr.o\
libc/lib_a-strsep.o\
libc/lib_a-strsignal.o\
libc/lib_a-strspn.o\
libc/lib_a-strstr.o\
libc/lib_a-strtod.o\
libc/lib_a-strtok.o\
libc/lib_a-strtok_r.o\
libc/lib_a-strtol.o\
libc/lib_a-strtold.o\
libc/lib_a-strtoll.o\
libc/lib_a-strtoll_r.o\
libc/lib_a-strtoul.o\
libc/lib_a-strtoull.o\
libc/lib_a-strtoull_r.o\
libc/lib_a-strupr.o\
libc/lib_a-strxfrm.o\
libc/lib_a-svfiprintf.o\
libc/lib_a-svfiscanf.o\
libc/lib_a-svfiwprintf.o\
libc/lib_a-svfiwscanf.o\
libc/lib_a-svfprintf.o\
libc/lib_a-svfscanf.o\
libc/lib_a-svfwprintf.o\
libc/lib_a-svfwscanf.o\
libc/lib_a-swab.o\
libc/lib_a-swprintf.o\
libc/lib_a-swscanf.o\
libc/lib_a-syscalls.o\
libc/lib_a-sysclose.o\
libc/lib_a-sysexecve.o\
libc/lib_a-sysfcntl.o\
libc/lib_a-sysfork.o\
libc/lib_a-sysfstat.o\
libc/lib_a-sysgetpid.o\
libc/lib_a-sysgettod.o\
libc/lib_a-sysisatty.o\
libc/lib_a-syskill.o\
libc/lib_a-syslink.o\
libc/lib_a-syslseek.o\
libc/lib_a-sysopen.o\
libc/lib_a-sysread.o\
libc/lib_a-syssbrk.o\
libc/lib_a-sysstat.o\
libc/lib_a-system.o\
libc/lib_a-systimes.o\
libc/lib_a-sysunlink.o\
libc/lib_a-syswait.o\
libc/lib_a-syswrite.o\
libc/lib_a-tdelete.o\
libc/lib_a-tdestroy.o\
libc/lib_a-telldir.o\
libc/lib_a-tfind.o\
libc/lib_a-time.o\
libc/lib_a-timelocal.o\
libc/lib_a-timesr.o\
libc/lib_a-tmpfile.o\
libc/lib_a-tmpnam.o\
libc/lib_a-toascii.o\
libc/lib_a-tolower.o\
libc/lib_a-toupper.o\
libc/lib_a-towctrans.o\
libc/lib_a-towlower.o\
libc/lib_a-towupper.o\
libc/lib_a-trap.o\
libc/lib_a-truncate.o\
libc/lib_a-tsearch.o\
libc/lib_a-twalk.o\
libc/lib_a-tzlock.o\
libc/lib_a-tzset.o\
libc/lib_a-tzset_r.o\
libc/lib_a-tzvars.o\
libc/lib_a-u_strerr.o\
libc/lib_a-unctrl.o\
libc/lib_a-ungetc.o\
libc/lib_a-ungetwc.o\
libc/lib_a-unlinkr.o\
libc/lib_a-usleep.o\
libc/lib_a-valloc.o\
libc/lib_a-vallocr.o\
libc/lib_a-vasiprintf.o\
libc/lib_a-vasniprintf.o\
libc/lib_a-vasnprintf.o\
libc/lib_a-vasprintf.o\
libc/lib_a-vdiprintf.o\
libc/lib_a-vdprintf.o\
libc/lib_a-vfiprintf.o\
libc/lib_a-vfiscanf.o\
libc/lib_a-vfiwprintf.o\
libc/lib_a-vfiwscanf.o\
libc/lib_a-vfprintf.o\
libc/lib_a-vfscanf.o\
libc/lib_a-vfwprintf.o\
libc/lib_a-vfwscanf.o\
libc/lib_a-viprintf.o\
libc/lib_a-viscanf.o\
libc/lib_a-vprintf.o\
libc/lib_a-vscanf.o\
libc/lib_a-vsiprintf.o\
libc/lib_a-vsiscanf.o\
libc/lib_a-vsniprintf.o\
libc/lib_a-vsnprintf.o\
libc/lib_a-vsprintf.o\
libc/lib_a-vsscanf.o\
libc/lib_a-vswprintf.o\
libc/lib_a-vswscanf.o\
libc/lib_a-vwprintf.o\
libc/lib_a-vwscanf.o\
libc/lib_a-wbuf.o\
libc/lib_a-wcpcpy.o\
libc/lib_a-wcpncpy.o\
libc/lib_a-wcrtomb.o\
libc/lib_a-wcscasecmp.o\
libc/lib_a-wcscat.o\
libc/lib_a-wcschr.o\
libc/lib_a-wcscmp.o\
libc/lib_a-wcscoll.o\
libc/lib_a-wcscpy.o\
libc/lib_a-wcscspn.o\
libc/lib_a-wcsdup.o\
libc/lib_a-wcsftime.o\
libc/lib_a-wcslcat.o\
libc/lib_a-wcslcpy.o\
libc/lib_a-wcslen.o\
libc/lib_a-wcsncasecmp.o\
libc/lib_a-wcsncat.o\
libc/lib_a-wcsncmp.o\
libc/lib_a-wcsncpy.o\
libc/lib_a-wcsnlen.o\
libc/lib_a-wcsnrtombs.o\
libc/lib_a-wcspbrk.o\
libc/lib_a-wcsrchr.o\
libc/lib_a-wcsrtombs.o\
libc/lib_a-wcsspn.o\
libc/lib_a-wcsstr.o\
libc/lib_a-wcstod.o\
libc/lib_a-wcstok.o\
libc/lib_a-wcstol.o\
libc/lib_a-wcstold.o\
libc/lib_a-wcstoll.o\
libc/lib_a-wcstoll_r.o\
libc/lib_a-wcstombs.o\
libc/lib_a-wcstombs_r.o\
libc/lib_a-wcstoul.o\
libc/lib_a-wcstoull.o\
libc/lib_a-wcstoull_r.o\
libc/lib_a-wcswidth.o\
libc/lib_a-wcsxfrm.o\
libc/lib_a-wctob.o\
libc/lib_a-wctomb.o\
libc/lib_a-wctomb_r.o\
libc/lib_a-wctrans.o\
libc/lib_a-wctype.o\
libc/lib_a-wcwidth.o\
libc/lib_a-wmemchr.o\
libc/lib_a-wmemcmp.o\
libc/lib_a-wmemcpy.o\
libc/lib_a-wmemmove.o\
libc/lib_a-wmemset.o\
libc/lib_a-wordexp.o\
libc/lib_a-wordfree.o\
libc/lib_a-wprintf.o\
libc/lib_a-writer.o\
libc/lib_a-wscanf.o\
libc/lib_a-wsetup.o\
libc/lib_a-xpg_strerror_r.o
